name: memcached
description: Simple in-memory key to object cache with expiry
version: 1.0.2
homepage: https://github.com/ArcaneArts/memcached
environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  synchronized: ^3.0.0+3
